package com.app.spark.constants

object IntentConstant {
    val POSITION="position"
    val PICTURE="picture"
    val FROM_CHAT="fromChat"
    val SELECTED_USER_ID="selectedUserId"
    val CHAT_TYPE= "chatType"
    val CHAT_TYPE_DATE= "chatTypeDate"
    val VIDEO_URL="video_url"
    val POST_ID="post_id"
    val POST_DETAIL="post_detail"
    val FLICK_DETAIL="flick_detail"
    val MIME_TYPE="mime_type"
    val REQUEST_CODE=110
    val MEDIA_TYPE="media_type"
    val MEDIA_URI="media_uri"
    const val POST_TYPE="post_type"
    const val IMPORTANT_DATA="important_model"
    const val SIGNUP_TYPE="signup_type"
    const val EMAIL_PHONE="email_phone"
    const val PROFILE_BIO="profile_bio"
    const val PROFILE_USERNAME="user_name"
    const val PROFILE_ID="user_is"
    const val IS_FOLLOWERS="isFollowers"
    const val FOLLOW_LIST="isFollowList"
    const val CHAT_ID="chatId"
    const val CHAT_NAME="chat_profile_name"
    const val CHAT_IMG="chat_img"
    const val FOLLOWING_GROUP="following_group"
    const val ISPAGE_THROUGH="open_page"
    const val PAGE_FLAG="flag_page"
    const val USERNAME="username"
    const val MOBILE="mobile"
    const val PASSWORD="password"
    var FeedValue=""

}