package com.app.spark.constants

object ServerConstant {
    val GROUP_NAME="group_name"
    const val SIGNUP = "signup"
    const val VERIFY_OTP = "verifyOtp"
    const val SIGNIN = "signin"
    const val COMPLETE_PROFILE = "completeProfile"
    const val UPDATE_DEVICE_TOKEN = "updateToken"
    const val EDIT_SIGNUP = "editsignup"
    const val VERIFY_USERNAME = "checkfieldExist"
    const val COUNTRY_STATE_LIST = "countrystateList"
    const val POPULAR_PROFILE = "getpopularProfile"
    const val FOLLOW_UNFOLLOW = "followUnfollow"
    const val EDIT_BIO_PROFILE = "editprofile"
    const val PROFILE_GET = "getProfile"
    const val POST_FEED = "postFeed"
    const val FOLLOWING_FOLLOWER_GET = "getfollowFollowers"
    const val GET_FEEDS = "getFeed"
    const val FEED_LIKE_ACTION = "feedlikeAction"
    const val FEED_COMMENT = "postComment"
    const val REPORT = "reportUser"
    const val REPORT_FEED = "reportFeed"
    const val BLOCK_USER = "blockuserAction"
    const val NOTIFICATION_LIST = "getNotification"
    const val FOLLOW_GROUP_CONNECTION_TYPE = "folowgroupAction"
    const val GET_COMMENTS = "getComment"
    const val COMMENTS_LIKE_ACTION = "commentlikeAction"
    const val SEARCH_USER = "searchUser"
    const val DELETE_COMMENT = "deleteComment"
    const val POST_FLICK = "postFlick"
    const val GET_FLICKS = "getFlick"
    const val VIEW_COUNT = "viewCount"
    const val CREATE_GROUP = "createGroup"
    const val UPLOAD_MEDIA = "uploadMedia"
    const val DELETE_FEED = "deleteFeed"
    const val GET_PROFILE_POST = "getprofilePost"
    const val SEND_OTP = "sendOTP"
    const val RESET_PASSWORD = "resetPassword"
    const val UPDATE_PERSONAL_INFO = "updatePersonalinfo"
    const val ADD_WORK_EXP = "addWorkExp"
    const val ADD_EDUCATION = "addEdu"
    const val UPDATE_PROFESSIONAL_INFO = "updateProfessionalinfo"
    const val ONLINE_STATUS = "userOnlineStatus"
    const val TAG_LIST = "getTagsByType"
    const val MATCHING_PEREFRENCES = "match"
    const val UPDATE_TAGS = "updateUserTags"
    const val UPDATE_ENGAGE="updateIsEngage"
    const val GET_STORIES="getStories"
    const val CREATE_ROOM="createRoom"
    const val ADD_STORY="postStory"
    const val GET_ADDUSER_FOLLOWER="getfollowFollowers"
    const val GET_ROOM_LIST="getRooms"   //getRoom
    const val ADD_USER_TO_ROOM="addToRoom"
    const val DELETE_ROOM="deleteRoom"
    const val GET_LIST="listRoom"
    const val REQUEST_LIST_ROOM="showRoomRequest"
    const val SET_RAISE_HAND="addRoomRequest"
    const val ACCEPTED_ROOM_REQUEST="acceptRoomRequest"
    const val REMOVE_FROM_ROOM="removeFromRoom"
    const val CHANGE_ROOM_USER_TYPE="changeRoomUserType"


    /************ Socket Events  */
    const val EVENT_CONVERSATION_LIST = "conversationList"
    const val EVENT_INITIATE_CHAT = "initChat"
    const val EVENT_GET_CHAT_LIST = "getChatList"
    const val EVENT_SEND_MESSAGE = "sendMessage"
    const val EVENT_RECEIVE_MESSAGE = "receiveMessage"
    const val EVENT_DELETE_NORMAL = "deletenormal"
    const val EVENT_DELETE_MSG = "deletemsg"
    const val EVENT_DELETE_MSG_EVERYONE = "deletefor_everyone"
    const val EVENT_MUTE_NOTIFICATION = "mutenotification"
    const val EVENT_PIN_USERS = "pinusers"
    const val EVENT_DELETE_GROUP = "delete_group"
    const val EVENT_CLEAR_CHAT = "clearchat"
    const val EVENT_BLOCK_CHAT = "blockUser"
    const val EVENT_REPORT_CHAT = "reportChat"
    const val EVENT_EXIT_GROUP = "exit_group"
    const val EVENT_USER_DETAIL = "UserDetail"
    const val EVENT_GROUP_DETAIL = "GroupDetail"

    const val ROOM_LISTINER = "sendRoomMessage"
    const val RECEIVE_ROOM_MSG="receiveHomeMessage"
    const val ROOM_CHAT_TYPE="room"

    /************ API Params  */
    const val RECEIVER_ID = "id"
    const val SENDER_ID = "s_id"
    const val CHAT_TYPE = "chat_type"
    const val MESSAGE = "msg"
    const val CHAT_MESSAGE = "message"
    const val MESSAGE_TYPE = "msg_type"
    const val THUMBNAIL_URL = "thumb_url"
    const val MEDIA_URL = "url"
    const val MEDIA_TYPE = "media_type"

    var SELECT_TYPE=""
}